"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROI_TBL = exports.WITHDRAW_GATEWAY_TBL = exports.USER_WITHDRAW_GATEWAY_TBL = exports.USER_WITHDRAW_TBL = exports.USER_REFERRAL_TBL = exports.USER_PAIR_TBL = exports.USER_KYC_TBL = exports.USER_DEPOSIT_TBL = exports.USER_TREE_TBL = exports.USER_TBL = exports.TRANSACTION_TBL = exports.TICKET_MESSAGE_TBL = exports.TICKET_TBL = exports.SETTING_TBL = exports.REPORT_REQUEST_TBL = exports.PAYMENT_TRANSFER_TBL = exports.PLAN_HISTORY_TBL = exports.PLAN_TBL = exports.OTP_TBL = exports.AUTOMATIC_DEPOSIT_GATEWAY_TBL = exports.MANUAL_DEPOSIT_GATEWAY_TBL = exports.LOGIN_SESSION_TBL = exports.KYC_SETTING_TBL = exports.FRONTEND_SETTING_TBL = exports.FAQ_LIST_TBL = void 0;
exports.FAQ_LIST_TBL = "faq_list";
exports.FRONTEND_SETTING_TBL = "frontend_setting";
exports.KYC_SETTING_TBL = "kyc_setting";
exports.LOGIN_SESSION_TBL = "login_session";
exports.MANUAL_DEPOSIT_GATEWAY_TBL = "manual_deposit_gateway";
exports.AUTOMATIC_DEPOSIT_GATEWAY_TBL = "online_deposit_gateway";
exports.OTP_TBL = "otp";
exports.PLAN_TBL = "plan";
exports.PLAN_HISTORY_TBL = "plan_history";
exports.PAYMENT_TRANSFER_TBL = "payment_transfer";
exports.REPORT_REQUEST_TBL = "report_request";
exports.SETTING_TBL = "setting";
exports.TICKET_TBL = "ticket";
exports.TICKET_MESSAGE_TBL = "ticket_message";
exports.TRANSACTION_TBL = "transaction";
exports.USER_TBL = "user";
exports.USER_TREE_TBL = "user_tree";
exports.USER_DEPOSIT_TBL = "user_deposit";
exports.USER_KYC_TBL = "user_kyc";
exports.USER_PAIR_TBL = "user_pair_income";
exports.USER_REFERRAL_TBL = "user_referral_income";
exports.USER_WITHDRAW_TBL = "user_withdraw";
exports.USER_WITHDRAW_GATEWAY_TBL = "user_withdraw_gateway";
exports.WITHDRAW_GATEWAY_TBL = "withdraw_gateway";
exports.ROI_TBL = "roi_income";
